default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: shuinstagram_development

test:
  <<: *default
  database: shuinstagram_test

production:
  <<: *default
  database: shuinstagram_production
  username: shuinstagram
  password: <%= ENV['TWC_DATABASE_PASSWORD'] %>
